// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI-powered tool that analyzes user profiles and suggests relevant skills to highlight.
 *
 * - skillsOptimizer - A function that handles the skill optimization process.
 * - SkillsOptimizerInput - The input type for the skillsOptimizer function.
 * - SkillsOptimizerOutput - The return type for the skillsOptimizer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SkillsOptimizerInputSchema = z.object({
  profileDescription: z
    .string()
    .describe('A detailed description of the user profile, including skills, experience, and career goals.'),
  industryTrends: z
    .string()
    .describe('Information about current industry trends and in-demand skills.'),
});
export type SkillsOptimizerInput = z.infer<typeof SkillsOptimizerInputSchema>;

const SkillsOptimizerOutputSchema = z.object({
  suggestedSkills: z
    .array(z.string())
    .describe('A list of skills suggested to highlight based on the profile and industry trends.'),
  reasoning: z
    .string()
    .describe('Explanation of why these skills are suggested, based on the provided information.'),
});
export type SkillsOptimizerOutput = z.infer<typeof SkillsOptimizerOutputSchema>;

export async function skillsOptimizer(input: SkillsOptimizerInput): Promise<SkillsOptimizerOutput> {
  return skillsOptimizerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'skillsOptimizerPrompt',
  input: {schema: SkillsOptimizerInputSchema},
  output: {schema: SkillsOptimizerOutputSchema},
  prompt: `You are an AI-powered career advisor specializing in portfolio optimization.

You will analyze the user's profile description and current industry trends to suggest the most relevant skills to highlight in their portfolio.

Based on the provided information, suggest a list of skills that the user should highlight in their portfolio to improve visibility and opportunities.

Profile Description: {{{profileDescription}}}
Industry Trends: {{{industryTrends}}}

Explain why each skill is suggested, referencing both the profile and industry trends.
`,
});

const skillsOptimizerFlow = ai.defineFlow(
  {
    name: 'skillsOptimizerFlow',
    inputSchema: SkillsOptimizerInputSchema,
    outputSchema: SkillsOptimizerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
